site_name: Documentação

copyright: Logo and Favicon made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>

repo_name: fga-eps-mds/2021-2-SysArq-Doc
repo_url: https://github.com/fga-eps-mds/2021-2-SysArq-Doc/

edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: stylesheets/assets/logo.png

  favicon: stylesheets/assets/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.top
  
extra_css:
  - stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fga-eps-mds/2021-2-SysArq-Doc/

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Artefatos:
    - Product Backlog: product_backlog.md
      - Risco:
        - Planejamento: planejamento.md
  - Sprints:
    - Semana1:
      - Planejamento: semana1/planejamento.md
    - Semana2:
      - Planejamento: semana2/planejamento.md
    - Sprint1:
      - Planning: sprint1/planejamento.md
      - Review: sprint1/revisao.md
      - Retrospective: sprint1/retrospectiva.md
    - Sprint1:
      - Planning: sprint2/planejamento.md
      - Review: sprint2/revisao.md
      - Retrospective: sprint2/retrospectiva.md
  - Políticas do Repositório: 
    - Como contribuir: contributing.md
    - Código de conduta: code_of_conduct.md
